apiVersion: v1
kind: Service
metadata:
  name: url-shortener-api
  namespace: api
  labels:
    app: url-shortener-api
spec:
  selector:
    app: url-shortener-api
  ports:
    - name: http          
      protocol: TCP
      port: 8080          
      targetPort: 8080
  type: ClusterIP
