apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: url-shortener-api
  namespace: monitoring
  labels:
    app: url-shortener-api
    release: monitoring
spec:
  selector:
    matchLabels:
      app: url-shortener-api
  namespaceSelector:
    matchNames:
      - api
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
      scrapeTimeout: 10s
